---
# ---Kubernetes-specific variables---

# This variable specificies which Kubernetes platform Ascender and its components will be installed on.
k8s_platform: k3s # Options include k3s, eks and dkp, with more to come.

# Routable IP address for the K8s API Server
# (This could be a Load Balancer if using 3 K8s control nodes)
kubeapi_server_ip: "127.0.0.1"

# This value being set to "true" means that some work needs to be done to set up a
# cluster before proceeding. Here is ther behavior for different values of k8s_platforms:
# k3s: A single-node k3s cluster will be set up on the inventory server
#      named "ascender_host"
# eks: N/A, as this is handled by the EKS_CLUSTER_STATUS variable
# rke2: N/A, as you must use Labyrinth Labs' Ansible role to set up a fresh kubernetes cluster
kube_install: false

# Firewall Disable - For most K8s installs, firewalls are recommended to be disabled, set this to false if
# if you need the firewall to stay enabled
firewalld_disable: true

# Specify an INTERNAL container registry and namespace where the k8s cluster can access Ascender images
k8s_container_registry: ""

# Indictates whether or not the kubeconfig file needs to be downloaded to the Ansible controller
download_kubeconfig: false

# ---k3s variables---

# IP address for the K3s Master/Worker node
# Required for local DNS and k3s install
# This IP Address must be close reachable by the server from which this installer is running
k3s_master_node_ip: "127.0.0.1"

# Whether to use the ClusterIP and Ingress rules to access Ascender
# or access it via NodePort
# Valid entries are ClusterIP or NodePort
k3s_service_type: ClusterIP

# ---eks variables---

# Determines whether to use Route53's Domain Management (which is automated)
# Or a third-party service (e.g., Cloudflare, GoDaddy, etc.)
#If this value is set to false, you will have to manually set a CNAME record for 
# {{ASCENDER_HOSTNAME }} and {{ LEDGER_HOSTNAME }} to point to their corresponding
# AWS Loadbalancers
USE_ROUTE_53: yes

# If desired, this indicates an AWS IAM user that can be set up in order to have minimum 
# permissions to set up a new eks cluster and install Ascender and its associoated components
EKS_USER: ascenderuser

# The name of the eks cluster to set up
EKS_CLUSTER_NAME: ascender-eks-cluster

# Determines what to do with the eks cluster Ascender wil be installed on:
# provision: Provision a new EKS cluster from scratch
# configure: use the cluster specified by the variable EKS_CLUSTER_NAME, and configure it with 
#            policies for loa balancer creation and elastic block service access
# no_action: use the cluster specified by the variable EKS_CLUSTER_NAME, but make no changes to it before
#            installing Ascender.
EKS_CLUSTER_STATUS: no_action

# The AWS region hosting the eks cluster
EKS_CLUSTER_REGION: us-east-1

# The eks cluster subnet in CIDR notation
# Only required if EKS_CLUSTER_STATUS is set to provision.
EKS_CLUSTER_CIDR: "10.10.0.0/16"

    # Determines whether cluster nodes are assigned public IPs.
    # If this value is set to true, cluster nodes will be assigned public IPs.
EKS_PUBLIC: false

    # The number of subnets for the eks cluster
EKS_NUM_SUBNETS: 3

    # The network size for each of the subnets
EKS_SUBNET_SIZE: 26

    # Set the SSL Policy for the EKS AWS Load Balancer
EKS_SSL_POLICY: "ELBSecurityPolicy-TLS13-1-2-Res-2021-06"

    # Whether to set up an Internet Gateway for the VPC
EKS_INTERNET_GATEWAY: true

    # The security groups to use for the AWS Load Balancer; this controls who can access the Load Balancer and therefore Ascender.
    # If left blank, the installer will create a security group that allows access from anywhere
#EKS_ALB_SECURITY_GROUPS: ""

    # The inbound CIDR blocks for the AWS Load Balancer security group; this controls who can access the Load Balancer and therefore Ascender.
EKS_ALB_INBOUND_CIDRS: ["0.0.0.0/0"]

# The kubernetes version for the eks cluster; available kubernetes versions can be found here:
# https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html
EKS_K8S_VERSION: "1.33"

# The worker node instance types 
EKS_INSTANCE_TYPE: t3.large

# The minimum number of worker nodes that the cluster will run
EKS_MIN_WORKER_NODES: 2

# The maximum number of worker nodes that the cluster will run
EKS_MAX_WORKER_NODES: 6

# The desired number of worker nodes for the eks cluster
EKS_NUM_WORKER_NODES: 3

# The size of the Elastic Block Storage volume for each worker node
EKS_WORKER_VOLUME_SIZE: 100

# The Amazon Elastic Block Store Container Storage Interface (CSI) Driver provides
# a CSI interface used by Container Orchestrators to manage the lifecycle of Amazon EBS volumes.
# This variable specifies the version in use by the cluster; all releases can be found here:
# https://github.com/kubernetes-sigs/aws-ebs-csi-driver/releases
EKS_EBS_CSI_DRIVER_VERSION: "v1.48.0"

# The default storage class to use for Ascender PVCs. This will determine the type of EBS volume
# that Ascender uses for its storage. Valid options are gp2, gp3 and io2, which correspond to the
# EBS volume types. If this variable is not set, the installer will not create a default storage
# class and you will have to set the storage class for the Ascender PVCs manually.
EKS_DEFAULT_STORAGE_CLASS: gp3


# ---dkp variables---
# The name of the dkp cluster you wish to deploy Ascender to and/or create
# See a list of all dkp clusters with the command 
# NOTE: This must be done while pointing to the DKP Bootstrap Cluster
DKP_CLUSTER_NAME: dkp-cluster

# ---rke2 variables---

# The URL to the binary file rke2.linux-amd64. If you want to choose a different 
# release, you can choose here:
# https://github.com/rancher/rke2/releases
RKE2_BINARY_URL: https://github.com/rancher/rke2/releases/download/v1.25.16%2Brke2r1/rke2.linux-amd64

# A directory in which to place both temporary artifacts
# and timestamped Kubernetes Manifests to make Ascender/Ledger easy
# to uninstall
tmp_dir: "{{ playbook_dir }}/../ascender_install_artifacts"

required_collections:
  - name: amazon.aws
    version: "6.5.0"
    compare: ">="
    version_type: semver
    platform: ["eks"]
  - name: ansible.posix
    version: "1.5.4"
    compare: ">="
    version_type: semver
    platform: ["azure", "dkp", "eks", "gcp", "k3s", "rke2"]
  - name: awx.awx
    version: "22.3.0"
    compare: ">="
    version_type: semver
    platform: ["azure", "dkp", "eks", "gcp", "k3s", "rke2"]
  - name: azure.azcollection
    version: "2.4.0"
    compare: ">="
    version_type: semver
    platform: ["azure"]
  - name: community.aws
    version: "11.0.0"
    compare: ">="
    version_type: semver
    platform: ["eks"]
  - name: community.general
    version: "8.3.0"
    compare: ">="
    version_type: semver
    platform: ["azure", "dkp", "eks", "gcp", "k3s", "rke2"]
  - name: google.cloud
    version: "1.3.0"
    compare: ">="
    version_type: semver
    platform: ["gcp"]
  - name: kubernetes.core
    version: "2.4.0"
    compare: ">="
    version_type: semver
    platform: ["azure", "dkp", "eks", "gcp", "k3s", "rke2"]

# For development purposes
SKIP_DISK_CHECK: false
