---
# ---Kubernetes-specific variables---

# This variable specificies which Kubernetes platform Ascender and its components will be installed on.
k8s_platform: dkp # Options include k3s and dkp, with more to come.

# The name of the dkp cluster you wish to deploy Ascender to and/or create
# See a list of all dkp clusters with the command 
# # kubectl get clusters -A
# NOTE: This must be done while pointing to the DKP Bootstrap Cluster
DKP_CLUSTER_NAME: dkp-cluster

