---
# This variable specificies which Kubernetes platform Ascender and its components will be installed on.
k8s_platform: gke
# Boolean indicating whether or not the kubeconfig file needs to be downloaded to the Ansible controller
download_kubeconfig: true
# Determines whether to use Google Cloud DNS Domain Management (which is automated)
# Or a third-party service (e.g., Cloudflare, GoDaddy, etc.)
# If this value is set to false, you will have to manually set an A record for
# {{ASCENDER_HOSTNAME }} and {{ LEDGER_HOSTNAME }} to point to the Google Cloud
# Loadbalancers
USE_GOOGLE_DNS: true
# The name of the gke cluster to install Ascender on - if it does not already exist, the installer can set it up
GKE_CLUSTER_NAME: ascender-gke-cluster
# Specifies whether the GKE cluster needs to be provisioned (provision), exists but needs to be configured to support Ascender (configure), or exists and needs nothing done before installing Ascender (no_action)
GKE_CLUSTER_STATUS: provision
# The Google Cloud zone hosting the gke cluster
GKE_CLUSTER_ZONE: 
# The kubernetes version for the gke cluster
GKE_K8S_VERSION: "1.29.4-gke.1043002"
# The gke worker node instance types
GKE_INSTANCE_TYPE: "e2-medium"
# The desired number of gke worker nodes
GKE_NUM_WORKER_NODES: 3
# The volume size of gke worker nodes in GB
GKE_WORKER_VOLUME_SIZE: 100
