# Copyright (c) 2024, Ctrl IQ, Inc. All rights reserved.

- name: Ensure Correct architecture for K3s Target
  ansible.builtin.import_playbook: assertions.yml
  
- name: Ensure Kubernetes Cluster Access
  ansible.builtin.import_playbook: kubernetes_setup.yml
