---
# This variable specificies which Kubernetes platform Ascender and its components will be installed on.
k8s_platform: aks
# Boolean indicating whether or not the kubeconfig file needs to be downloaded to the Ansible controller
download_kubeconfig: true
# Determines whether to use Azure DNS Domain Management (which is automated)
# Or a third-party service (e.g., Cloudflare, GoDaddy, etc.)
# If this value is set to false, you will have to manually set an A record for
# {{ASCENDER_HOSTNAME }} and {{ LEDGER_HOSTNAME }} to point to the Azure
# Loadbalancers
USE_AZURE_DNS: true
# The name of the eks cluster to install Ascender on - if it does not already exist, the installer can set it up
AKS_CLUSTER_NAME: ascender-aks-cluster
# Specifies whether the AKS cluster needs to be provisioned (provision), exists but needs to be configured to support Ascender (configure), or exists and needs nothing done before installing Ascender (no_action)
AKS_CLUSTER_STATUS: provision
# The Azure region hosting the aks cluster
AKS_CLUSTER_REGION: eastus
# The kubernetes version for the aks cluster; available kubernetes versions can be found here:
AKS_K8S_VERSION: "1.29"
# The aks worker node instance types
AKS_INSTANCE_TYPE: "Standard_D2_v2"
# The desired number of aks worker nodes
AKS_NUM_WORKER_NODES: 3
# The volume size of aks worker nodes in GB
AKS_WORKER_VOLUME_SIZE: 100
